version: "3.3"
services:
  backend:
    container_name: fastapi_backend
    build:
      context: backend/backendapp
      dockerfile: backend.dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8018"]
    ports:
      - 8018:8018
    depends_on:
      - fastapi_db
    networks:
      - fastapi_network
  fastapi_db:
    container_name: fastapi_db
    image: postgres:12.0-alpine
#    volumes:
#      - /postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fastapi_db
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge

#  api:
#    container_name: api
#    build: ./vue_backend
#    command: python manage.py runserver 0.0.0.0:8000
##    command: gunicorn -c gunicorn_config.py vuebackend.wsgi:application
##    command: gunicorn vuebackend.wsgi:application --bind 127.0.0.1:8005
#    volumes:
#      - ./vue_backend/:/usr/src/api/
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - db
#      - redis
#    networks:
#      - django-nginx