"""add product model fields

Revision ID: 0336f293591c
Revises: 64d6ec06a2ba
Create Date: 2020-12-25 21:52:06.490454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0336f293591c'
down_revision = '64d6ec06a2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('color', sa.String(length=64), nullable=True))
    op.add_column('product', sa.Column('material', sa.String(length=128), nullable=True))
    op.add_column('product', sa.Column('seo_description', sa.String(length=1024), nullable=True))
    op.add_column('product', sa.Column('seo_title', sa.String(length=256), nullable=True))
    op.drop_index('ix_product_name', table_name='product')
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.create_index('ix_product_name', 'product', ['name'], unique=True)
    op.drop_column('product', 'seo_title')
    op.drop_column('product', 'seo_description')
    op.drop_column('product', 'material')
    op.drop_column('product', 'color')
    # ### end Alembic commands ###
