"""add product

Revision ID: 0b651ca7ca0b
Revises: 239705dbd98b
Create Date: 2020-12-25 18:22:57.009756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b651ca7ca0b'
down_revision = '239705dbd98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
