"""add foreignkey user

Revision ID: 239705dbd98b
Revises: f6936e20206e
Create Date: 2020-12-24 23:47:42.448562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239705dbd98b'
down_revision = 'f6936e20206e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usermodel', 'departmentmodel', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usermodel', type_='foreignkey')
    op.drop_column('usermodel', 'department_id')
    # ### end Alembic commands ###
