"""init data

Revision ID: 466d591b81d0
Revises: 
Create Date: 2021-01-05 23:18:31.229988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466d591b81d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('parent_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('departmentmodel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departmentmodel_id'), 'departmentmodel', ['id'], unique=False)
    op.create_index(op.f('ix_departmentmodel_name'), 'departmentmodel', ['name'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('seo_title', sa.String(length=256), nullable=True),
    sa.Column('seo_description', sa.String(length=1024), nullable=True),
    sa.Column('material', sa.String(length=128), nullable=True),
    sa.Column('color', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_number'), 'product', ['number'], unique=True)
    op.create_table('usermodel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departmentmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermodel_id'), 'usermodel', ['id'], unique=False)
    op.create_index(op.f('ix_usermodel_name'), 'usermodel', ['name'], unique=False)
    op.create_index(op.f('ix_usermodel_phone'), 'usermodel', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermodel_phone'), table_name='usermodel')
    op.drop_index(op.f('ix_usermodel_name'), table_name='usermodel')
    op.drop_index(op.f('ix_usermodel_id'), table_name='usermodel')
    op.drop_table('usermodel')
    op.drop_index(op.f('ix_product_number'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_departmentmodel_name'), table_name='departmentmodel')
    op.drop_index(op.f('ix_departmentmodel_id'), table_name='departmentmodel')
    op.drop_table('departmentmodel')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
