"""refactor product foreignkey name

Revision ID: 64d6ec06a2ba
Revises: 33edfde91c4f
Create Date: 2020-12-25 21:25:50.316329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d6ec06a2ba'
down_revision = '33edfde91c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_product_sub_category_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'subcategory', ['sub_category_id'], ['id'])
    op.drop_column('product', 'product_sub_category_id')
    op.add_column('subcategory', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('subcategory_product_category_id_fkey', 'subcategory', type_='foreignkey')
    op.create_foreign_key(None, 'subcategory', 'category', ['category_id'], ['id'])
    op.drop_column('subcategory', 'product_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('product_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subcategory', type_='foreignkey')
    op.create_foreign_key('subcategory_product_category_id_fkey', 'subcategory', 'category', ['product_category_id'], ['id'])
    op.drop_column('subcategory', 'category_id')
    op.add_column('product', sa.Column('product_sub_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_product_sub_category_id_fkey', 'product', 'subcategory', ['product_sub_category_id'], ['id'])
    op.drop_column('product', 'sub_category_id')
    # ### end Alembic commands ###
