"""add product

Revision ID: dacb084be73c
Revises: 0b651ca7ca0b
Create Date: 2020-12-25 18:31:20.269670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacb084be73c'
down_revision = '0b651ca7ca0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productcategorymodel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productcategorymodel_id'), 'productcategorymodel', ['id'], unique=False)
    op.create_index(op.f('ix_productcategorymodel_name'), 'productcategorymodel', ['name'], unique=True)
    op.create_table('productsubcategorymodel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('product_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_category_id'], ['productcategorymodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productsubcategorymodel_id'), 'productsubcategorymodel', ['id'], unique=False)
    op.create_index(op.f('ix_productsubcategorymodel_name'), 'productsubcategorymodel', ['name'], unique=True)
    op.create_table('productmodel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('product_sub_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_sub_category_id'], ['productsubcategorymodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productmodel_id'), 'productmodel', ['id'], unique=False)
    op.create_index(op.f('ix_productmodel_name'), 'productmodel', ['name'], unique=True)
    op.create_index(op.f('ix_productmodel_number'), 'productmodel', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productmodel_number'), table_name='productmodel')
    op.drop_index(op.f('ix_productmodel_name'), table_name='productmodel')
    op.drop_index(op.f('ix_productmodel_id'), table_name='productmodel')
    op.drop_table('productmodel')
    op.drop_index(op.f('ix_productsubcategorymodel_name'), table_name='productsubcategorymodel')
    op.drop_index(op.f('ix_productsubcategorymodel_id'), table_name='productsubcategorymodel')
    op.drop_table('productsubcategorymodel')
    op.drop_index(op.f('ix_productcategorymodel_name'), table_name='productcategorymodel')
    op.drop_index(op.f('ix_productcategorymodel_id'), table_name='productcategorymodel')
    op.drop_table('productcategorymodel')
    # ### end Alembic commands ###
