"""init commit two

Revision ID: f6936e20206e
Revises: 
Create Date: 2020-12-24 23:39:59.658350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6936e20206e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departmentmodel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departmentmodel_id'), 'departmentmodel', ['id'], unique=False)
    op.create_index(op.f('ix_departmentmodel_name'), 'departmentmodel', ['name'], unique=False)
    op.create_table('usermodel',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermodel_id'), 'usermodel', ['id'], unique=False)
    op.create_index(op.f('ix_usermodel_name'), 'usermodel', ['name'], unique=False)
    op.create_index(op.f('ix_usermodel_phone'), 'usermodel', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermodel_phone'), table_name='usermodel')
    op.drop_index(op.f('ix_usermodel_name'), table_name='usermodel')
    op.drop_index(op.f('ix_usermodel_id'), table_name='usermodel')
    op.drop_table('usermodel')
    op.drop_index(op.f('ix_departmentmodel_name'), table_name='departmentmodel')
    op.drop_index(op.f('ix_departmentmodel_id'), table_name='departmentmodel')
    op.drop_table('departmentmodel')
    # ### end Alembic commands ###
